### ISSUE TITLE
Could not find class: apple.awt.CGraphicsEnvironment

### ISSUE THREAD

**Issue by julioz** [akonior/icon-version#2]
When building the app with the newly added plugin (version 1.0.1), I receive the a `BUILD FAILED` message alongside with the following error:
```
Could not find class: apple.awt.CGraphicsEnvironment
```

I'm building it against Android Studio v. `1.1.0`.

What could it be? I would love to integrate this plugin into my app.

**Comment by akonior** [comment]
Fixed with the newest plugin version: 1.1.1
