### ISSUE TITLE
Feature request: Allow custom text

### ISSUE THREAD

**Issue by milosmns** [akonior/icon-version#7]
It would be very helpful to have a custom text written on the icon, for example I would like to have 3 rows of custom text. Can you add that please? A good way would be to do it through the icon-version config

**Comment by akonior** [comment]
Hi @milosmns thanks for suggestion. Sounds good. Unfortunately I don't have time resources now. Will think about it in the future. Thx.

**Comment by dalewking** [comment]
In my case I would just like to add a third line with the version code, which seems like an easy thing to add.

**Comment by dalewking** [comment]
So, because of this and several other issues I ended up writing my own plugin, based on this that is much more customizable and fixes several problems with this plugin.

See https://gitlab.com/NobleworksSoftware/icon-overlay-plugin

**Comment by akonior** [comment]
@dalewking Awesome! I'm happy that my code helped you. Thx.

**Comment by milosmns** [comment]
@dalewking Why is it on gitlab? Any specific reason?

**Comment by dalewking** [comment]
@milosmns Because I do not support the political agenda that GitHub promotes (something a tech company has no business doing), so I moved all my repositories to GitLab and with rare exceptions refuse to put any of my own work on GitHub servers.

Any specific reason it shouldn't be on GitLab?

**Comment by milosmns** [comment]
No, I was just curious :)
